### ISSUE TITLE
Strage error while trying to get component running

### ISSUE THREAD

**Issue by thundergreen** [Anonym-tsk/homeassistant-climate-xiaomi-remote#1]
Hi Thanks for this HACS integration but I face a strange error.

I setup remote and it is working. But once I add climate hassio tell me that /config/configuration.yaml does not exist. Here my config:

```
climate:
#  - platform: smartir
#    name: Smart IR 
#    unique_id: bedroom_ac
#    device_code: 1001
#    controller_data: remote.remote_bedroom
#    temperature_sensor: sensor.temperature_bedroom
#    humidity_sensor: sensor.humidity_bedroom
#    power_sensor: binary_sensor.ac_power
#  - platform: cozytouch
#    username: thundergreen@googlemail.com
#    password: cozytouch

############## AC ROSE #######################

  - platform: xiaomi_remote
    name: Air Conditioner Rose
    remote: remote.remote_rose
#    temp_sensor: sensor.multisensor_rose_temperature
    commands: !include Hitachi.yaml
    min_temp: 16
    max_temp: 32
#    target_temp: 21
#    target_temp_step: 1
    hvac_mode: 'off'
#    fan_mode: low
    customize:
      hvac_modes:
        - cool
        - heat
        - dry
        - auto
        - fan_only
        - 'off'
      fan_modes:
        - low
        - medium
        - high
        - auto

################### AC BEDROOM ###########################

  - platform: xiaomi_remote
    name: Air Conditioner Bedroom
#    temp_sensor: sensor.multisensor_bedroom_temperature
    remote: remote.remote_bedroom
    commands: !include Hitachi.yaml
#    min_temp: 16
#    max_temp: 32
#    target_temp: 21
#    target_temp_step: 1
    hvac_mode: 'off'
#    fan_mode: low
    customize:
      hvac_modes:
        - cool
        - heat
        - dry
        - auto
        - fan_only
        - 'off'
      fan_modes:
        - low
        - medium
        - high
        - auto

############### AC EVAN ###################################

  - platform: xiaomi_remote
    name: Air Conditioner Evan
    remote: remote.remote_evan
#    temp_sensor: sensor.multisensor_evan_temperature
    commands: !include Hitachi.yaml
    min_temp: 16
    max_temp: 32
#    target_temp: 21
#    target_temp_step: 1
    hvac_mode: 'off'
#    fan_mode: low
    customize:
      hvac_modes:
        - cool
        - heat
        - dry
        - auto
        - fan_only
        - 'off'
      fan_modes:
        - low
        - medium
        - high
        - auto
```

Remote is working
