### ISSUE TITLE
Last state is not saved

### ISSUE THREAD

**Issue by CooleRnax** [Anonym-tsk/homeassistant-climate-xiaomi-remote#4]
I have just upgraded from 0.93.
Upgraded this component too.
I have an issue that state is not saved between ha restarts.
After restart component climate start with initial state.

My config:
```
climate:
  - platform: xiaomi_remote
    name: ac_name
    remote: remote.name
    commands: !include ir_remote_codes/climate/Daikin.yaml
    temp_sensor: sensor.temperature_name
    min_temp: 20
    max_temp: 25
    target_temp: 24
    target_temp_step: 1
    # hvac_mode: auto
    # fan_mode: auto
    customize:
      hvac_modes:
        - auto
        - heat
        - cool
        - 'off'
      fan_modes:
        - auto
```
