### ISSUE TITLE
New restore state issue.

### ISSUE THREAD

**Issue by CooleRnax** [Anonym-tsk/homeassistant-climate-xiaomi-remote#5]
I have checked new version.
There are still some cases when it doesn't work.

If you turn off the ac and reboot.
After reboot ac will be turned on.

```
climate:
  - platform: xiaomi_remote
    name: ac_name
    remote: remote.name
    commands: !include ir_remote_codes/climate/Daikin.yaml
    temp_sensor: sensor.temperature_name
    min_temp: 20
    max_temp: 25
    target_temp: 24
    target_temp_step: 1
    hvac_mode: "off"
    fan_mode: auto
    customize:
      hvac_modes:
        - auto
        - heat
        - cool
        - 'off'
      fan_modes:
        - auto
```
